### ISSUE TITLE
Target IP

### ISSUE THREAD

**Issue by micha122** [bitfocus/companion-module-aten-matrix#1]
Hello,

unfortunately I can't get any further with the setup...
We have an Aten VM0404HA this I have connected via RS323 to USB with the computer. How do I now get the target IP address? I can control the device via PuTTY without any problems.

**Comment by krocheck** [comment]
Hi @micha122.  Since that model does not have an Ethernet port (as you've noted, just USB and RS232) you won't be able to control it with Companion.  Companion only supports control of devices via network control.
