### ISSUE TITLE
ATEN 4x4 VIDEO MATRIX SWITHC

### ISSUE THREAD

**Issue by vlada140** [bitfocus/companion-module-aten-matrix#3]
Hello,

is there companion module for ATEN 4x4 VIDEO MATRIX SWITCH - [LINK](https://www.aten.com/global/en/products/professional-audiovideo/video-matrix-switches/vm0404hb/)? Also, here is [user manual](https://assets.aten.com/product/manual/vm0404hb-vm0808hb_um_w_2021-11-25.pdf).

On their official page (link above) can be found diagram and all specification. Device can be controlled over network (web GUI, app), IR and RS232.

Thank you

**Comment by NoahCallaway** [comment]
Yes. This module will work with that device. You'll need to select it in the module configuration.
