### ISSUE TITLE
aten-matrix 2.0.1: when selecting a crosspoint, nothing happens and an error is created

### ISSUE THREAD

**Issue by rgischig** [bitfocus/companion-module-aten-matrix#8]
Setup:
3.3.0 (3.3.0+6991-stable-b27baf94)
on Raspi4 build

connecting to a VM0808HA matrix

Connection works fine, but when pressing a button an error is triggered, and no actions performed:

`24.05.30 13:28:58 Surface/Handler/streamdeck:CL50K2A02394: Button 55/0/1 pressed
24.05.30 13:28:58 Instance/Wrapper/aten: Error executing action: opt is not defined
24.05.30 13:28:58 Surface/Handler/streamdeck:CL50K2A02394: Button 55/0/1 released`

I think this started to happen after the update to 3.3.0
[CompanionPi_companion-config_20240530-1235.zip](https://github.com/bitfocus/companion-module-aten-matrix/files/15499156/CompanionPi_companion-config_20240530-1235.zip)

**Comment by NoahCallaway** [comment]
Hi @rgischig thanks for raising an issue.

I think I've found the issue that crept in whilst upgrading the module to support Companion v3. I've tagged [a new version](https://github.com/bitfocus/companion-module-aten-matrix/releases/tag/v2.0.2) and am just waiting for it to be included in the beta builds.

I'll let you know when it's included so you can test.

**Comment by NoahCallaway** [comment]
@rgischig This should now be fixed on the latest beta builds.
Let me know if you see any more issues.
